spring:
  application:
    name: feature-toggle-write
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/feature_toggle_write
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      group-id: feature-toggle-write

topics: # Topic do konsumowania
  feature-toggle-configuration-events: feature-toggle-configuration-events

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([${spring.application.name:-app}]){green} %clr([%X{correlationId:--}]){yellow} %clr([%X{actor:--}]){cyan} %clr(%-5level) -> %msg%n"

outbox:
  batch-size: 100
  pool-interval-ms: 10s
  initial-delay-ms: 0s
  attempt-limit: 3
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    client-id: feature-toggle-write-client
    topics: # Topic do wytwarzania
      - name: feature-toggle-events
        partitions: 3
        replication-factor: 1
    props:
      spring.json.add.type.headers: true

#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka.clients.consumer: DEBUG
server:
  port: 8082